import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Segoe UI", "Inter", "Helvetica Neue", "Arial", "sans-serif"],
        mono: ["SF Mono", "JetBrains Mono", "Fira Code", "Cascadia Code", "Consolas", "monospace"],
      },
      fontSize: {
        xs: ["11px", { lineHeight: "16px" }],
        sm: ["13px", { lineHeight: "18px" }],
        base: ["14px", { lineHeight: "20px" }],
        md: ["15px", { lineHeight: "22px" }],
        lg: ["17px", { lineHeight: "24px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "38px" }],
        "4xl": ["36px", { lineHeight: "44px" }],
        "5xl": ["48px", { lineHeight: "56px" }],
      },
      spacing: {
        "0": "0px",
        "px": "1px",
        "0.5": "2px",
        "1": "4px",
        "1.5": "6px",
        "2": "8px",
        "2.5": "10px",
        "3": "12px",
        "3.5": "14px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "7": "28px",
        "8": "32px",
        "9": "36px",
        "10": "40px",
        "12": "48px",
        "14": "56px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
        "32": "128px",
      },
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        "3xl": "24px",
        full: "9999px",
      },
      colors: {
        brand: {
          primary: "var(--brand-primary)",
          hover: "var(--brand-primary-hover)",
          active: "var(--brand-primary-active)",
          subtle: "var(--brand-primary-subtle)",
        },
        bg: {
          base: "var(--bg-base)",
          surface: "var(--bg-surface)",
          elevated: "var(--bg-elevated)",
          overlay: "var(--bg-overlay)",
          modal: "var(--bg-modal)",
          tooltip: "var(--bg-tooltip)",
          input: "var(--bg-input)",
          "input-focus": "var(--bg-input-focus)",
          sidebar: "var(--bg-sidebar)",
          "sidebar-hover": "var(--bg-sidebar-hover)",
          "sidebar-active": "var(--bg-sidebar-active)",
          card: "var(--bg-card)",
          "card-hover": "var(--bg-card-hover)",
          header: "var(--bg-header)",
          skeleton: "var(--bg-skeleton)",
          "skeleton-shimmer": "var(--bg-skeleton-shimmer)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          disabled: "var(--text-disabled)",
          inverse: "var(--text-inverse)",
          "on-brand": "var(--text-on-brand)",
          link: "var(--text-link)",
          "link-hover": "var(--text-link-hover)",
          placeholder: "var(--text-placeholder)",
          heading: "var(--text-heading)",
        },
        border: {
          default: "var(--border-default)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
          focus: "var(--border-focus)",
          divider: "var(--border-divider)",
        },
        icon: {
          default: "var(--icon-default)",
          muted: "var(--icon-muted)",
          strong: "var(--icon-strong)",
          brand: "var(--icon-brand)",
        },
        semantic: {
          success: {
            bg: "var(--semantic-success-bg)",
            bgSubtle: "var(--semantic-success-bgSubtle)",
            text: "var(--semantic-success-text)",
            textStrong: "var(--semantic-success-textStrong)",
            border: "var(--semantic-success-border)",
            icon: "var(--semantic-success-icon)",
          },
          warning: {
            bg: "var(--semantic-warning-bg)",
            bgSubtle: "var(--semantic-warning-bgSubtle)",
            text: "var(--semantic-warning-text)",
            textStrong: "var(--semantic-warning-textStrong)",
            border: "var(--semantic-warning-border)",
            icon: "var(--semantic-warning-icon)",
          },
          danger: {
            bg: "var(--semantic-danger-bg)",
            bgSubtle: "var(--semantic-danger-bgSubtle)",
            text: "var(--semantic-danger-text)",
            textStrong: "var(--semantic-danger-textStrong)",
            border: "var(--semantic-danger-border)",
            icon: "var(--semantic-danger-icon)",
          },
          info: {
            bg: "var(--semantic-info-bg)",
            bgSubtle: "var(--semantic-info-bgSubtle)",
            text: "var(--semantic-info-text)",
            textStrong: "var(--semantic-info-textStrong)",
            border: "var(--semantic-info-border)",
            icon: "var(--semantic-info-icon)",
          },
          neutral: {
            bg: "var(--semantic-neutral-bg)",
            text: "var(--semantic-neutral-text)",
            border: "var(--semantic-neutral-border)",
          },
        },
        finance: {
          income: "var(--finance-income)",
          expense: "var(--finance-expense)",
          savings: "var(--finance-savings)",
          debt: "var(--finance-debt)",
          neutral: "var(--finance-neutral)",
          positive: "var(--finance-positive)",
          negative: "var(--finance-negative)",
        },
        chart: {
          grid: "var(--chart-grid)",
          axis: "var(--chart-axis)",
          label: "var(--chart-label)",
          tooltip: "var(--chart-tooltip)",
          crosshair: "var(--chart-crosshair)",
          1: "#FF2D6B",
          2: "#6366F1",
          3: "#0EA5E9",
          4: "#10B981",
          5: "#F59E0B",
          6: "#EC4899",
          7: "#8B5CF6",
          8: "#14B8A6",
          9: "#F97316",
          10: "#A3E635",
        },
        
        // --- Legacy Shadcn Mappings (to reduce complete breakage) ---
        background: "var(--bg-base)",
        foreground: "var(--text-primary)",
        card: "var(--bg-card)",
        "card-foreground": "var(--text-primary)",
        popover: "var(--bg-surface)",
        "popover-foreground": "var(--text-primary)",
        primary: {
          DEFAULT: "var(--brand-primary)",
          foreground: "var(--text-on-brand)",
        },
        secondary: {
          DEFAULT: "var(--bg-sidebar-hover)",
          foreground: "var(--text-primary)",
        },
        muted: {
          DEFAULT: "var(--bg-overlay)",
          foreground: "var(--text-secondary)",
        },
        accent: {
          DEFAULT: "var(--bg-sidebar-active)",
          foreground: "var(--text-primary)",
        },
        destructive: {
          DEFAULT: "var(--semantic-danger-bg)",
          foreground: "var(--semantic-danger-text)",
        },
        input: "var(--bg-input)",
        ring: "var(--border-focus)",
      },
      boxShadow: {
        "xs": "0 1px 2px rgba(0,0,0,0.05)",
        "sm": "0 1px 4px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)",
        "md": "0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)",
        "lg": "0 8px 24px rgba(0,0,0,0.1), 0 2px 8px rgba(0,0,0,0.06)",
        "xl": "0 16px 40px rgba(0,0,0,0.12), 0 4px 12px rgba(0,0,0,0.06)",
        "overlay": "0 24px 64px rgba(0,0,0,0.15)",
        "brand": "0 4px 16px rgba(255,45,107,0.2)",
        "inner": "inset 0 1px 3px rgba(0,0,0,0.08)",
      },
      screens: {
        "sm": "480px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        slideUp: {
          from: { transform: "translateY(8px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          from: { transform: "translateY(0)", opacity: "1" },
          to: { transform: "translateY(8px)", opacity: "0" },
        },
        scaleIn: {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        scaleOut: {
          from: { transform: "scale(1)", opacity: "1" },
          to: { transform: "scale(0.95)", opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200%" },
          "100%": { backgroundPosition: "200%" },
        },
      },
      animation: {
        fadeIn: "fadeIn 180ms cubic-bezier(0, 0, 0.2, 1)",
        fadeOut: "fadeOut 120ms cubic-bezier(0.4, 0, 1, 1)",
        slideUp: "slideUp 250ms cubic-bezier(0.4, 0, 0.2, 1)",
        slideDown: "slideDown 120ms cubic-bezier(0.4, 0, 1, 1)",
        scaleIn: "scaleIn 180ms cubic-bezier(0.34, 1.56, 0.64, 1)",
        scaleOut: "scaleOut 120ms cubic-bezier(0.4, 0, 1, 1)",
        shimmer: "shimmer 1.5s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
