
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wulhjbwijgbticuslygm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bGhqYndpamdidGljdXNseWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMTQ5ODIsImV4cCI6MjA1MjY5MDk4Mn0.e1rPcOXFG27k7ui0xt2ZWGxPryEx1s0zEvjsvXeZENk";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
    },
    global: {
      headers: {
        'x-application-name': 'expendX',
      }
    }
  }
);
