
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wulhjbwijgbticuslygm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bGhqYndpamdidGljdXNseWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMTQ5ODIsImV4cCI6MjA1MjY5MDk4Mn0.e1rPcOXFG27k7ui0xt2ZWGxPryEx1s0zEvjsvXeZENk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'budget-app-auth-token'
    },
    // @ts-ignore - Ignore TypeScript errors for tables not yet in types
    global: {
      headers: { 'x-my-custom-header': 'budget-app' }
    }
  }
);

// Helper function to safely get a table reference, even if it's not in the types yet
export function getTable(tableName: string) {
  // @ts-ignore - Ignore TypeScript errors for tables not yet in types
  return supabase.from(tableName);
}
